name: Generate terraform docs
on:
    push:
      branches:
        - master
jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: master

        - name: Generate TF Docs
          uses: terraform-docs/gh-actions@v1.0.0
          with:
            working-dir: .
            indention: 3
            git-push: true